### ISSUE TITLE
Doesn't install on windows

### ISSUE THREAD

**Issue by Berserker66** [realitix/pyvma#1]
Due to lack of readme, I assume the installation is via setup.py install; however this results in:

    E:\pyvma-master>py -3.6 setup.py install
    error in pyvma setup command: '_cffi_build/pyvma_build.py:ffi': object 'ffi' not found in module

win10, python 3.6.2 64bit

**Comment by realitix** [comment]
Indeed it works only on linux currently.
When it will be done, I will realize the windows compatibility.

**Comment by realitix** [comment]
I have fixed the Windows build.
Can you try again ?

To build on Windows, you need to follow exactly these build advices: https://github.com/realitix/pyshaderc#installation
`pyshader` is another module I did and the installation follows the same process.

PS: You don't need cmake for `pyvma`

**Comment by Berserker66** [comment]
Standard build instructions for any C-python module never work for me, something about my setup isn't getting detected properly. I have to use this batch: 
https://pastebin.com/aDX69RzF
(which I used to build cython, numpy and various cython-modules, so I know it works generally)
However, in this case I get this result:
https://pastebin.com/4VNmTaxR

Which is either my setup or a problem with this module, I can't tell you, sorry.

**Comment by realitix** [comment]
Did you run `setup.py build` before `setup.py install` ? `build` generates the static library. It looks like you didn't do it.
When you use `pip`, you usually don't have this problem because `pip` runs the `build` command under the hood.

**Comment by Berserker66** [comment]
That would do it:
https://pastebin.com/4X1bQUAg

usually build means make the module locally and install means make the module in site-packages.
I've never encountered a module before where you have to build and then install.

**Comment by realitix** [comment]
Indeed, I overwrite the Build command because I think about build as "build the library". Moreover, `pip` automatically calls it. If it was just for local, `pip` wouldn't call the `build` command.

**Comment by realitix** [comment]
Currently it's just the cffi wrapper, I have to do the Python part.
