### ISSUE TITLE
doesn't install on windows, take 2

### ISSUE THREAD

**Issue by Berserker66** [realitix/pyvma#2]
So, yeah. With 2.0.0.0 it is broken for windows again:
https://i.imgur.com/fsMEAug.png

full log:
https://pastebin.com/WZXtbktt

**Comment by realitix** [comment]
Can you try again with `pyvma-2.0.0.1` (the last version) ? It works for me.

**Comment by Berserker66** [comment]
Got` package pyvma installed successfully` this time.
